[workspace]
resolver = "2"
members = [
    "src",
    "crates/nexterm-core",
    "crates/nexterm-pty",
    "crates/nexterm-terminal",
    "crates/nexterm-input",
    "crates/nexterm-renderer",
]

[workspace.package]
version      = "0.1.0"
edition      = "2021"
authors      = ["Akram <your@email.com>"]
license      = "MIT"
repository   = "https://github.com/yourusername/nexterm"
rust-version = "1.75"

[workspace.dependencies]
tokio        = { version = "1",  features = ["full"] }
winit        = "0.29"
wgpu         = "0.19"
portable-pty = "0.8"
cosmic-text  = "0.11"
serde        = { version = "1", features = ["derive"] }
serde_json   = "1"
toml         = "0.8"
tracing            = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow    = "1"
thiserror = "1"

[profile.release]
opt-level     = 3
lto           = true
codegen-units = 1
strip         = true